[build]
  base    = "frontend"     
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION  = "9"

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# OPTIONAL: only if you want same-origin /api/* to hit a remote API in prod.
# Remove entirely if you call VITE_API_URL directly from the frontend.
# [[redirects]]
#   from = "/api/*"
#   to   = "https://your-freqtrade-api.com/api/:splat"
#   status = 200
#   force = true

[context.production.environment]
  VITE_API_URL = "https://your-freqtrade-api.com"
  VITE_WS_URL  = "wss://your-freqtrade-api.com"

[context.deploy-preview.environment]
  VITE_API_URL = "https://staging-freqtrade-api.com"
  VITE_WS_URL  = "wss://staging-freqtrade-api.com"

[context.branch-deploy.environment]
  VITE_API_URL = "http://localhost:8080"
  VITE_WS_URL  = "ws://localhost:8080"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
